### ISSUE TITLE
AVR GCC failure

### ISSUE THREAD

**Issue by Lunaphied** [bad-alloc-heavy-industries/cxc-build#2]
Sorry for what's certainly going to be a fairly unhelpful description of this issue but build worked fine until hitting the avr build.
Uploaded the logs for stdout/error not sure how helpful they actually are.

Basically it seems it's somehow looking in the prefix specified + `/usr/include` which is... nothing. Nothing should be there, no idea why it's looking there. No idea how to address it further.
[cxc-build.stderr.log](https://github.com/bad-alloc-heavy-industries/cxc-build/files/7016829/cxc-build.stderr.log)
[cxc-build.stdout.log](https://github.com/bad-alloc-heavy-industries/cxc-build/files/7016830/cxc-build.stdout.log)

**Comment by dragonmux** [comment]
This is now fixed in 8d38f5ab3d88494f4ecbc230dbecd088c4993cdd
